/**:
  ros__parameters:
    # Waypoint Follower
    steering_kp: -4.0
    steering_ki: -0.7
    steering_kd: -0.7

    throttle_kp: 1.0
    throttle_ki: 0.5
    throttle_kd: 0.5

    waypoint_data_file: "waypoints.json"
    n_look_ahead: 5

    max_wheel_angle_rad: 1.0
    wheel_angle_change_rate: 1.0

    # Donkeysim Interface
    client_config_pkg: 'donkeysim_launch'
    client_config_file: 'param/donkeysim_client.yaml'
