/**:
  ros__parameters:
    # Joystick
    sticky_buttons: true

    # Donkeysim Interface
    client_config_pkg: 'donkeysim_launch'
    client_config_file: 'param/donkeysim_client.yaml'

    # JS TAI Interface
    axis_stick_steering: 0
    axis_trigger_throttle: 5
    axis_trigger_brake: 2
    steering_flipped: true
    throttle_flipped: true
    brake_flipped: true

    # Simple Mapping
    grid_size_m: 0.05
    max_displacement_m: 0.2
    max_rotation_deg: 10.0
    map_block_size_m: 5.0