builtin_interfaces/Time stamp

tai_interface/Throttle throttle 
# [0, 100] throttle paddle percentage

tai_interface/Brake brake 
# [0, 100] brake paddle percentage

tai_interface/Steer steering_openloop
# [-1, 1] open-loop steering where negative is left
#         and positive is right

tai_interface/Steer steering_rad 
#[-pi, pi] close-loop steering where negative is left 
#          and positive is right
